[package]
name = "dualsensectl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2.6.3"
rand = "0.8.5"
crc32fast = "1.4.2"
const-crc32 = "1.3.0"
bytemuck = { version = "1.17.0", features = ["derive", "min_const_generics"] }
